### ISSUE TITLE
Icons package needed

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-web#1]
We have icons in design as in the picture. We should add them to passwall-web.
![Screen Shot 2020-10-07 at 00 28 50](https://user-images.githubusercontent.com/3696314/95262040-1c3ccb80-0834-11eb-95a1-583d7f0292f7.png)

Does anyone want to work on this?

**Comment by hvsio** [comment]
I would like to take it!

**Comment by yakuter** [comment]
Great thank you @hvsio The designer used this page for icons. 
https://heroicons.dev/

So you shoud import their font package to get the same icons.
