### ISSUE TITLE
Gradient effects needed

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-web#2]
We have gradient effect in Pro title and border of Pro price table in design. We should add this to passwall-web.
![Screen Shot 2020-10-07 at 00 33 48](https://user-images.githubusercontent.com/3696314/95262437-cb79a280-0834-11eb-8f04-640a86ea09cf.png)

Does anyone want to work on this?

**Comment by rootEnginear** [comment]
I would like to work on this one. May I know the value of the border gradient too?

**Comment by yakuter** [comment]
> I would like to work on this one. May I know the value of the border gradient too?

Well you already figured it out. Thank you. 

Closed with #3
