### ISSUE TITLE
Layout is already Flexbox but needs some little touch to be responsive

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-web#4]
The project coded with flexbox but needs to be responsive as in the image.
![Screen Shot 2020-10-07 at 07 48 11](https://user-images.githubusercontent.com/3696314/95288739-c38c2380-0871-11eb-9d0f-2783769757be.png)

Does anyone want to work on this?

**Comment by tomwalsh-home** [comment]
@yakuter, @passwall, I'll handle this :)

**Comment by yakuter** [comment]
Great. Thank you @tomwalsh-home Let me share the mobile view of menu.
![Responsive - Hamburger Menu](https://user-images.githubusercontent.com/3696314/95309645-17a7ff80-0894-11eb-8f19-c03b9beabcca.png)
